* Introduction
* Step by Step
  1. [ ] create a new rails application
     #+BEGIN_SRC sh :tangle bin/010_create_new_rails_application.sh
       rails new cars --database postgresql
     #+END_SRC
  2. [ ] Copy this rails-markets-cars.org file into cars/
  3. [ ] Enable a JavaScript runtime in [[file:Gemfile][Gemfile]]
     
     You probably got a 'Could not find a JavaScript runtime.' message from the
     'rake about' command. Open [[file:../Gemfile][Gemfile]] with your text editor and enable 'therubyracer.'
     
     #+BEGIN_SRC ruby
       # See https://github.com/sstephenson/execjs#readme for more supported runtimes
       gem 'therubyracer', platforms: :ruby
     #+END_SRC
     
     You might open [[file:../Gemfile][Gemfile]] with Emacs, Vi, [[http://macromates.com/][TextMate]], etc. this way:
     #+BEGIN_EXAMPLE
       textmate ../../Gemfile
     #+END_EXAMPLE
  4. [ ] Examine your Rails installation
     #+BEGIN_SRC sh
       rake about
     #+END_SRC
  5. [ ] file:config/database.yml
     #+BEGIN_SRC conf
       template: template0
     #+END_SRC
  6. [ ] rake db:create
     #+BEGIN_SRC sh
       rake db:create
     #+END_SRC
  7. [ ] generate a home controller
     #+BEGIN_SRC sh :tangle bin/020_controller_home.sh :shebang #!/bin/sh
       rails generate controller home index login logout --skip-stylesheets
     #+END_SRC
  8. [ ] Set the default route to home/index in [[file:config/routes.rb][config/routes.rb]]
     
     Open [[file:config/routes.rb][config/routes.rb]]  with your text editor. You will see the following
     commented line near the top of the file:
     #+BEGIN_SRC ruby
       # root 'welcome#index'
     #+END_SRC
     
     Let's uncomment and change the application root view:

     #+BEGIN_SRC ruby
       root "home#index"
     #+END_SRC
     
     Now, Rails will direct vistors to the application to home/index. We are
     ready to start the Rails application and incorporate Twitter Bootstrap's
     stylesheets and JavaScript scripts.
  9. [ ] Enable [[http://rubygems.org/gems/bootstrap-sass][bootstrap-sass]] in [[file:Gemfile][Gemfile]]
     #+BEGIN_SRC ruby
       # See http://rubygems.org/gems/bootstrap-sass (July 2014)
       gem "bootstrap-sass", "~> 3.2.0.0"
     #+END_SRC
  10. [ ] bundle install
  11. [ ] Remove the app/assets/stylesheets/application.css file
      #+BEGIN_SRC sh
        rm app/assets/stylesheets/application.css file
      #+END_SRC
  12. [ ] Create a new [[file:app/assets/stylesheets/application.css.scss][app/assets/stylesheets/application.css.scss]] file
      #+BEGIN_SRC css
	@import "bootstrap";
	body { padding-top: 60px; }
      #+END_SRC
  13. [ ] Import bootstrap javascript in [[file:app/assets/javascripts/application.js][app/assets/javascripts/application.js]]
      #+BEGIN_SRC js
	//= require jquery
	//= require jquery_ujs
	//= require turbolinks
	//= require_tree .
	//
	// The following line Loads all Bootstrap javascripts
	// = require bootstrap
      #+END_SRC
  14. [ ] Overwrite app/views/layouts/application.html.erb with starter-template.html.erb
     
      starter-template.html.erb is Twitter Bootstrap's example merged
      with the default app/views/layouts/application.html.erb file that Rails generates.
     
      Here's the resulting [[file:app/views/layouts/application.html.erb]]:
      #+BEGIN_SRC html :tangle app/views/layouts/application.html.erb :padline no
        <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="description" content="">
            <meta name="author" content="">
            
            <link rel="icon" href="../../favicon.ico">
            
            <title>Bootstrap starter template</title>
            <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
            <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
            <%= csrf_meta_tags %>
            <style>
              body {
              padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
              }
            </style>  
          </head>
          
          <body>
            <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
              <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="#">Project name</a>
                </div>
                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                  </ul>
                </div><!--/.nav-collapse -->
              </div>
            </div>
            
            <div class="container">
              
              <%= yield %>
              
            </div> <!-- /container -->
            
          </body>
        </html>

      #+END_SRC

      The starter example layout uses a fixed width layout, which is introduced at [[http://twitter.github.io/bootstrap/scaffolding.html#layouts][scaffolding.html#layouts]].
  15. [ ] Enable `devise` gem in [[file:Gemfile][Gemfile]]
      1. [ ] Edit [[file:Gemfile][Gemfile]]
	 #+BEGIN_SRC ruby
	   gem 'devise', '~> 3.2.4' # July 2014, Rails 4.1.1
         #+END_SRC
      2. [ ] run bundle install
	 #+BEGIN_SRC sh
           bundle install
         #+END_SRC
  16. [ ] Run the Devise gem install generator
      #+BEGIN_SRC sh
	rails generate devise:install
      #+END_SRC
  17. [ ] Generate a User Model and generate routes for user activities
      #+BEGIN_SRC sh
	rails generate devise User
      #+END_SRC
  18. [ ] Run the devise_create_users database migration the was created by in the previous command
      #+BEGIN_SRC sh
	rake db:migrate
      #+END_SRC
  19. [ ] (Re)start the Rails server
      #+BEGIN_SRC 
	kill -USR1 `cat tmp/pids/server.pid `; rails server --daemon
      #+END_SRC
  20. [ ] Place sign up and sign out links on the home page file:app/views/home/index.html.erb
      #+BEGIN_SRC html :tangle /tmp/home_index.html.erb :padline no
	<h1>Home#index</h1>
	<%= Time.now %>
	<li><%= link_to "Sign Up", new_user_registration_path %></li>
	<li><%= link_to "Sign In", new_user_session_path %></li>
	<li><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %></li>
       
	<% if user_signed_in? %>
	You are signed in, current_user.id = <%= current_user.id %><br />
	user_session.keys => <%= user_session.keys %>
	<% end %>
      #+END_SRC
      - To verify if a user is signed in, use the following helper: user_signed_in?
      - See https://github.com/plataformatec/devise#controller-filters-and-helpers
      - file:../app/views/home/index.html.erb
      - For the current signed-in user, this helper is available: current_user
  21. [ ] ad scaffold
      #+BEGIN_SRC sh :tangle bin/generate_scaffold_ad.sh :shebang #!/bin/sh
        # <troydwill@gmail.com> July, 2014

        MODEL="ad"

        rails generate scaffold $MODEL \
            user_id:integer \
            year:integer \
            model_id:integer \
            mileage:integer \
            isforsale:boolean \
            isdealer:boolean \
            color_id:integer \
            city_id:integer \
            ad_url:string \
            ad_date:date \
            ad_price:integer \
            contact_name:string \
            contact_phone:string \
            contact_email:string \
            contact_log:text \
            notes:text \
            --skip-stylesheets
      #+END_SRC
  22. [ ] file:app/models/ad.rb
      #+BEGIN_SRC ruby :tangle /tmp/ad.rb
        validates :year, :presence => true, :numericality => true
        validates :user_id, :presence => true, :numericality => true
        validates :model_id, :presence => true, :numericality => true
        belongs_to :user
        belongs_to :model
        belongs_to :city
        belongs_to :color
      #+END_SRC
  23. [ ] rake db:migrate
  24. [ ] colors
      1. [ ] scaffold
	 #+BEGIN_SRC sh
           rails generate scaffold color name:string --skip-stylesheets
         #+END_SRC
      2. [ ] file:app/models/color.rb
	 #+BEGIN_SRC ruby
	   validates :name, :presence => true, :uniqueness => true
	 #+END_SRC
      3. [ ] rake db:migrate
      4. [ ] file:app/views/ads/_form.html.erb
	 #+BEGIN_SRC html
           <%= select("ad", "color_id", Color.all.collect { |p| [p.name, p.id]}) %>
	 #+END_SRC
  25. [-] models
      1. [ ] scaffold
	 #+BEGIN_SRC sh :tangle bin/generate_scaffold_model.sh :shebang #!/bin/sh	 
           rails generate scaffold model \
                   user_id:integer \
                   make_id:integer \
                   name:string \
                   image_url:string \
                   wikipedia:string \
                   url:string \
                   --skip-stylesheets
	 #+END_SRC
      2. [ ] file:app/models/model.rb
	 #+BEGIN_SRC ruby
           validates :user_id, :presence => true, :numericality => true
           validates :make_id, :presence => true, :numericality => true
           validates :name, :presence => true
           belongs_to :make
	 #+END_SRC
      3. [ ] rake db:migrate
      4. [ ] file:app/views/ads/_form.html.erb
	 #+BEGIN_SRC html
           <%= select("ad", "model_id", Model.all.collect { |p| [p.name, p.id]}) %>
	 #+END_SRC
      4. [ ] file:app/views/models/_form.html.erb
	 #+BEGIN_SRC html
           <%= select("model", "make_id", Make.all.collect { |p| [p.name, p.id]}) %>
	 #+END_SRC
  26. [-] makes
      1. [ ] scaffold
	 #+BEGIN_SRC sh :tangle bin/generate_scaffold_make.sh :shebang #!/bin/sh	 
           rails generate scaffold make \
                   user_id:integer \
                   name:string \
                   url:string \
                   --skip-stylesheets
	 #+END_SRC
      2. [ ] file:app/models/make.rb
	 #+BEGIN_SRC ruby
           validates :user_id, :presence => true, :numericality => true
           validates :name, :presence => true, :uniqueness => true
           has_many :models
	 #+END_SRC
      3. [ ] rake db:migrate
      4. [ ] file:app/views/models/_form.html.erb
	 #+BEGIN_SRC html
           <%= select("ad", "make_id", Make.all.collect { |p| [p.name, p.id]}) %>
	 #+END_SRC
  27. [ ] cities
      1. [ ] scaffold
	 #+BEGIN_SRC sh :tangle bin/generate_scaffold_city.sh :shebang #!/bin/sh	 
           rails generate scaffold city \
                   name:string \
                   --skip-stylesheets
	 #+END_SRC
      2. [ ] file:app/models/city.rb
	 #+BEGIN_SRC ruby
           validates :name, :presence => true, :uniqueness => true
           has_many :ads
	 #+END_SRC
      3. [ ] rake db:migrate
      4. [ ] file:app/views/ads/_form.html.erb
	 #+BEGIN_SRC html
           <%= select("ad", "city_id", City.all.collect { |p| [p.name, p.id]}) %>
	 #+END_SRC
  28. [ ] file:app/views/ads/index.html.erb
      #+BEGIN_SRC html
        <h1>Your Vehicles</h1>

        <table>
          <tr>
            <th>Price</th>
            <th>Vehicle</th>
            <th>Miles</th>
            <th>Contact<br />phone</th>
            <th></th>
            <th></th>
          </tr>

          <% @ads.each do |ad| %>
          <tr>
            <td style="text-align: right; color:#A0522D;"><%= number_to_currency ad.ad_price, :precision => 0 %></td>
            <td><%= ad.year %> <%= link_to "#{ad.model.make.name} #{ad.model.name}", ad.ad_url %>, <%= link_to "#{ad.city.name}", "/cities/#{ad.city.id}" %></td>
            <td style="text-align: right; color:#A0522D; font-style:italic"><%= number_to_human ad.mileage, :precision => 0 %></td>
            <td><%= ad.contact_phone %></td>
            <td><%= link_to 'Show', ad %> / <%= link_to 'D', ad, :confirm => 'Are you sure?', :method => :delete %></td>
          </tr>
          <% end %>
        </table>

        <br />

        <%= link_to 'New Ad', new_ad_path %>

        <!-- ad.year -->
        <!-- ad.model_id -->
        <!-- ad.mileage -->
        <!-- ad.isforsale -->
        <!-- ad.city_id -->
        <!-- ad.ad_url -->
        <!-- ad.ad_date -->
        <!-- ad.ad_price -->
        <!-- ad.contact_name -->
        <!-- ad.contact_phone -->
        <!-- ad.contact_email -->
        <!-- ad.contact_log -->
        <!-- ad.notes -->
      #+END_SRC
